name: Docker Image
on:
  push:
    branches: ["master", "develop"]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          repository: phamhieu/inbucket
          push: false
          tag_with_ref: true
